### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by khalil-shao** [WellenWoo/StyleTransferGui#1]
你好，请问你的依赖库的版本是多少？
方便提供一下吗？

**Comment by ningbaimofan** [comment]
请问各个包都是什么版本的

**Comment by WellenWoo** [comment]
wxPython~=4.2.0
torch~=2.0.1
torchvision~=0.15.2
Pillow~=9.5.0
numpy~=1.24.3

在以上的依赖库下是可以正常运行的

**Comment by usemyhand** [comment]
module 'torchvision.models.vgg' has no attribute 'cfg'怎么解决
